name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build project
      run: |
        dotnet build src-installer/RDPWInst.dproj
        dotnet build src-rdpcheck/RDPCheck.dproj
        dotnet build src-rdpconfig/RDPConf.dproj
        dotnet build src-x86-binarymaster/rdpwrap.dproj
        dotnet build src-x86-x64-Fusix/RDPWrap.vcxproj

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: bin/
